# Generated by Django 5.2.15 on 2026-06-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='order_type',
            field=models.CharField(default='takeaway', max_length=20),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='table_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
